version: '3.6'
services:
  server:
    image: bofh
    build:
      context: .
    restart: unless-stopped
    stop_grace_period: 1s
    volumes:
      - ./:/code
    environment:
      - PORT=8000
      - ENV=development
    ports:
      - 8000:8000